### ISSUE TITLE
PUT /api/v1/event/에서 summary가 변경되지 않음

### ISSUE THREAD

**Issue by call-me-bammer** [SWM-15th-Dnight/main_backend#26]
# Result
클라이언트에서 일정 수정 기능 구현 중, 스웨거에서 `PUT /api/v1/event/` API를 테스트 하면서 event의 `summary`가 변경되지 않는 이슈가 있습니다.

# How

`calendarId` 2번의 `eventId` 52번 event에 대해 아래 request body로 테스트 했습니다. 200 코드를 받고 다른 필드는 전부 변경되는데 `summary`만 이전 값인 '저녁 식사'에서 바뀌지 않습니다.

```
{
  "eventId": 52,
  "summary": "제목이 전혀 바뀌지 않아!",
  "startAt": "2024-08-26T00:00:00",
  "endAt": "2024-08-26T00:00:01",
  "description": "스트링",
  "priority": 9,
  "status": "TENTATIVE",
  "transp": "OPAQUE",
  "calendarId": 2
}
```

# Screenshot

![image](https://github.com/user-attachments/assets/90692ed5-64a5-4d63-8629-1bb806a97341)

**Comment by inmonim** [comment]
해당 문제는 event/service 로직 내에서 update 진행 시, summary를 수정하는 코드를 누락하여 발생했음.

해당 로직을 수행하는 코드를 작성하여 문제를 해결함.
