### ISSUE TITLE
TimeZone 관련 설정 문제? 잘모르겠네요

### ISSUE THREAD

**Issue by koderpark** [SWM-15th-Dnight/main_backend#32]
지금 시각은 0928(토) 03시 14분입니다.
새벽 작업 도중에 일정을 음성으로 추가해봤는데
"오늘" 을 어제인 0927로 인식합니다.
AI 서버 거치고 오면서 chatgpt 쪽의 날짜 Timezone를 따르는 듯 한데, 그거 말고 다른 원인이 있을지도 모르겠어요.

**Comment by inmonim** [comment]
AI 서버의 타임존이 UTC로 설정되어 문제가 발생되는 것으로 파악. AI 서버의 시간대를 수정하겠음.
