### ISSUE TITLE
some /eventList/ handler returns false response

### ISSUE THREAD

**Issue by koderpark** [SWM-15th-Dnight/main_backend#33]
아마 기존 캘린더를 삭제하고 새 캘린더를 하나 임의 생성한 뒤에 발생하는 에러인거 같아요
삭제된 캘린더를 쿼리하고 있거나 한거같은데 확인해주시면 좋을듯
![image](https://github.com/user-attachments/assets/155716aa-bd8e-451a-922d-e01647094268)

**Comment by koderpark** [comment]
+ 월~금인 긴 일정에 대한 쿼리에서 error가 발생합니다.
지난번에 소마센터에서 해결했던 이슈랑 비슷하게 trace가 계속 쌓이네요 얘도
![image](https://github.com/user-attachments/assets/48fb8f2b-ef8a-40f2-88ec-2f9660f96932)

**Comment by koderpark** [comment]
- 캘린더 목록에서 캘린더를 삭제한 이후
- 날짜가 여러 개인 이벤트를 캘린더에 추가한 이후
원인으로 추측가는게 이거 두개입니다.

**Comment by inmonim** [comment]
현재의 모든 문제는 기본적으로 color set에 대한 로직이 제대로 잡혀있지 않아서 생기고 있음. 단순히 기본값을 추가하는 것으로 임시변통이 가능하나, 빠르게 로직을 정상화 해보겠음.

또한 스택 트레이스가 쌓이는 문제는 현재 수정했으나 dev서버에 반영이 안 되어 있음. 보다 빠르게 해결 가능
